_prefs: 
  mapid: ammeurer.5d704af1
  saveCenter: false
_properties: {}
attribution: "<a href='http://mapbox.com/about/maps' target='_blank'>Terms & Feedback</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 12.5039
  - 41.887
  - 18
description: Modified Pencil style to look old
format: jpeg80
interactivity_layer: ''
layers: null
maxzoom: 19
minzoom: 12
name: Pencil - LOTR
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,mapbox.mapbox-bathymetry-v1"
styles: 
  - style.mss
  - road.mss
  - terrain.mss
  - var.mss
  - label.mss
template: ''
